theme = "blowfish"
baseURL = "https://metalcyanide.github.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
